---
namespace: "tcharl"
name: "servicemesh"
version: "2.0.1"
description: "Deploys Istio mesh on a kubernetes cluster"

authors:
  - "Charlie Mordant <cmordant1@gmail.com>"

repository: "https://github.com/OsgiliathEnterprise/servicemesh"
documentation: "https://github.com/OsgiliathEnterprise/servicemesh/blob/master/README.md"
homepage: "https://github.com/OsgiliathEnterprise/servicemesh"
issues: "https://github.com/OsgiliathEnterprise/servicemesh/issues"

readme: "README.md"
license:
  - "Apache-2.0"
tags:
  - "istio"
  - "calico"
  - "cloud"
