---
- name: Converge master
  hosts: all
  vars:
    hostname_reboot: false
    kube_firewall_zone: 'public'
    master_preferred_nic: "eth1"
    standalone_role: False
    preferred_nic: "eth1"
#        kube_alt_names:
#          - "kubeadm.osgiliath.net"
  roles:
    - role: tcharl.servicemesh
