---
- name: Converge master
  hosts:
    - kube_master
  vars:
    hostname_reboot: false
    master_preferred_nic: "eth1"
    preferred_nic: "eth1"
#        kube_alt_names:
#          - "kubeadm.osgiliath.net"
  roles:
    - role: tcharl.servicemesh
