---

- name: Prepare
  hosts:
    - kube_master
    - kube_node
  tasks:
    - include_role:
        name: tcharl.servicemesh
        tasks_from: requirements.yml
      vars:
        secure_logs: False
        preferred_nic: "eth1"
        company_domain: osgiliath.test
        company_realm_password: '123ADMin'
        company_ad_password: '123ADmPass'
        standalone_role: True
